### ISSUE TITLE
RequestInterface::getParameter returns array

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio-engine#1]
According to the PHPdoc of [RequestInterface::getParameter](https://github.com/apioo/fusio-engine/blob/620825d0068017e6695dd07d7cafb2590907caab/src/RequestInterface.php#L64) the functions always returns a string.
This is not true for query parameters like ```?filter[customer]=25```, in which case getParameter returns an array. 
IMHO the array return value is fine, but PHPDoc should be changed to ```@return string|array```.
also [Request::getParamter](https://github.com/apioo/fusio-engine/blob/620825d0068017e6695dd07d7cafb2590907caab/src/Request.php#L115) should be updated.

**Comment by chriskapp** [comment]
Yes this is true. I have justed improved the documentation at several classes also the leading PHP doc is always provided at the interface and the implementing class uses now a simple `@inheritdoc`. Please take a look at the [RequestInterface::getParameter](https://github.com/apioo/fusio-engine/blob/master/src/RequestInterface.php#L80). If you find more mistakes at the PHP docs please let me know.
